{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datasynth.fullname" . }}-api-keys
  labels:
    {{- include "datasynth.labels" . | nindent 4 }}
type: Opaque
data:
  api-keys: {{ join "," .Values.apiKeys | b64enc | quote }}
{{- end }}
