apiVersion: v1
kind: Service
metadata:
  name: {{ include "datasynth.fullname" . }}
  labels:
    {{- include "datasynth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.restPort }}
      targetPort: http-rest
      protocol: TCP
      name: http-rest
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "datasynth.selectorLabels" . | nindent 4 }}
