//! Artifact accumulator for generated audit data.
//!
//! [`ArtifactBag`] collects the typed artifacts produced by step dispatchers
//! during an FSM engagement run.  Its fields mirror the audit subset of the
//! `AuditSnapshot` used by the enhanced orchestrator, but only include the
//! types that the FSM engine actually generates.

use serde::{Deserialize, Serialize};

use datasynth_core::models::audit::{
    AnalyticalProcedureResult, AuditEngagement, AuditEvidence, AuditFinding, AuditProcedureStep,
    AuditSample, CombinedRiskAssessment, ConfirmationResponse, EngagementLetter,
    ExternalConfirmation, GoingConcernAssessment, MaterialityCalculation, ProfessionalJudgment,
    RiskAssessment, SampledItem, SamplingPlan, SubsequentEvent, Workpaper,
};
use datasynth_standards::audit::opinion::{AuditOpinion, KeyAuditMatter};

/// Single account balance for trial balance output within the audit context.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrialBalanceEntry {
    pub account_code: String,
    pub account_description: String,
    #[serde(with = "rust_decimal::serde::str")]
    pub debit_balance: rust_decimal::Decimal,
    #[serde(with = "rust_decimal::serde::str")]
    pub credit_balance: rust_decimal::Decimal,
    #[serde(with = "rust_decimal::serde::str")]
    pub net_balance: rust_decimal::Decimal,
    pub entity_code: String,
    pub period: String,
}

/// Accumulates audit artifacts generated by the [`StepDispatcher`] during an
/// engagement run.
///
/// Each field corresponds to a single artifact type.  The bag starts empty
/// (`Default`) and grows as the engine walks through FSM steps.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ArtifactBag {
    /// Audit engagements (ISA 210/220).
    pub engagements: Vec<AuditEngagement>,
    /// Engagement letters (ISA 210).
    pub engagement_letters: Vec<EngagementLetter>,
    /// Materiality calculations (ISA 320).
    pub materiality_calculations: Vec<MaterialityCalculation>,
    /// Individual risk assessments (ISA 315/330).
    pub risk_assessments: Vec<RiskAssessment>,
    /// Combined risk assessments linking IR + CR (ISA 315).
    pub combined_risk_assessments: Vec<CombinedRiskAssessment>,
    /// Workpapers / audit documentation (ISA 230).
    pub workpapers: Vec<Workpaper>,
    /// Audit evidence records (ISA 500).
    pub evidence: Vec<AuditEvidence>,
    /// Audit findings / deficiencies (ISA 265).
    pub findings: Vec<AuditFinding>,
    /// Professional judgment records (ISA 200).
    pub judgments: Vec<ProfessionalJudgment>,
    /// Sampling plans (ISA 530).
    pub sampling_plans: Vec<SamplingPlan>,
    /// Individual sampled items within a plan (ISA 530).
    pub sampled_items: Vec<SampledItem>,
    /// Analytical procedure results (ISA 520).
    pub analytical_results: Vec<AnalyticalProcedureResult>,
    /// Going concern assessments (ISA 570).
    pub going_concern_assessments: Vec<GoingConcernAssessment>,
    /// Subsequent events (ISA 560).
    pub subsequent_events: Vec<SubsequentEvent>,
    /// Audit opinions (ISA 700/705/706).
    pub audit_opinions: Vec<AuditOpinion>,
    /// Key audit matters (ISA 701).
    pub key_audit_matters: Vec<KeyAuditMatter>,
    /// Procedure steps executed within workpapers (ISA 330).
    pub procedure_steps: Vec<AuditProcedureStep>,
    /// Audit samples drawn during testing (ISA 530).
    pub samples: Vec<AuditSample>,
    /// External confirmations sent (ISA 505).
    pub confirmations: Vec<ExternalConfirmation>,
    /// Confirmation responses received (ISA 505).
    pub confirmation_responses: Vec<ConfirmationResponse>,

    /// Journal entry population referenced by sampling and analytical procedures.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub journal_entries: Vec<datasynth_core::models::JournalEntry>,

    /// Trial balance derived from journal entries.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub trial_balance_entries: Vec<TrialBalanceEntry>,
}

impl ArtifactBag {
    /// Total number of artifacts across all categories.
    pub fn total_artifacts(&self) -> usize {
        self.engagements.len()
            + self.engagement_letters.len()
            + self.materiality_calculations.len()
            + self.risk_assessments.len()
            + self.combined_risk_assessments.len()
            + self.workpapers.len()
            + self.evidence.len()
            + self.findings.len()
            + self.judgments.len()
            + self.sampling_plans.len()
            + self.sampled_items.len()
            + self.analytical_results.len()
            + self.going_concern_assessments.len()
            + self.subsequent_events.len()
            + self.audit_opinions.len()
            + self.key_audit_matters.len()
            + self.procedure_steps.len()
            + self.samples.len()
            + self.confirmations.len()
            + self.confirmation_responses.len()
            + self.journal_entries.len()
            + self.trial_balance_entries.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_bag_is_empty() {
        let bag = ArtifactBag::default();
        assert_eq!(bag.total_artifacts(), 0);
    }
}
